import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import weather from '../styles/Weather.module.css'
import Header from '../components/jsdocs/Header';
import Body from '../components/jsdocs/Body';

export default function Home() {
  return (
    <div className={weather.all_page}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={weather.container}>
        <main>
          <Header />
          <Body />
        </main>
      </div>
    </div>
  )
}